name: CI

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ staging, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Lint
        run: |
          python -m pip install ruff
          ruff check app || true
      - name: Unit tests
        run: |
          python - << 'PY'
import requests, sys
print("No tests yet - add pytest later")
PY
      - name: Build Docker image
        run: docker build -t hello-world-app:ci .

  publish:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/hello-world-app
          TAG=${GITHUB_SHA::7}
          docker build -t $IMAGE:$TAG -t $IMAGE:latest .
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest
